### ISSUE TITLE
Where is the Addepar/RedFlag@v1 github action ?

### ISSUE THREAD

**Issue by manishsingh10895** [Addepar/RedFlag#9]
Hi, 

I was trying to go through the readme examples. After configuring `aws-credentials` action. I was searching for the `Addepar/RedFlag@v1` github action. I couldn't find it anywhere. Is it private  maybe ?

The example `ci.yml` doesn't work and shows the error ,  cannot find `Addepar/RedFlag@v1` action.

Thanks.

**Comment by addepar-tg** [comment]
Hi @manishsingh10895, thanks for reporting!

We have bumped the version and added meta-tag `v1`, so you should now be able to use the action `Addepar/RedFlag@v1`.  Please let us know if there are any issues.

Thank you.
